// World capitals and major cities
// type: 'capital' | 'major'
export const CITIES = [
  // --- EUROPE ---
  { name: 'London', lat: 51.51, lng: -0.13, type: 'capital', country: 'GB' },
  { name: 'Paris', lat: 48.86, lng: 2.35, type: 'capital', country: 'FR' },
  { name: 'Berlin', lat: 52.52, lng: 13.41, type: 'capital', country: 'DE' },
  { name: 'Rome', lat: 41.90, lng: 12.50, type: 'capital', country: 'IT' },
  { name: 'Madrid', lat: 40.42, lng: -3.70, type: 'capital', country: 'ES' },
  { name: 'Amsterdam', lat: 52.37, lng: 4.90, type: 'capital', country: 'NL' },
  { name: 'Brussels', lat: 50.85, lng: 4.35, type: 'capital', country: 'BE' },
  { name: 'Vienna', lat: 48.21, lng: 16.37, type: 'capital', country: 'AT' },
  { name: 'Stockholm', lat: 59.33, lng: 18.07, type: 'capital', country: 'SE' },
  { name: 'Oslo', lat: 59.91, lng: 10.75, type: 'capital', country: 'NO' },
  { name: 'Copenhagen', lat: 55.68, lng: 12.57, type: 'capital', country: 'DK' },
  { name: 'Helsinki', lat: 60.17, lng: 24.94, type: 'capital', country: 'FI' },
  { name: 'Warsaw', lat: 52.23, lng: 21.01, type: 'capital', country: 'PL' },
  { name: 'Prague', lat: 50.08, lng: 14.44, type: 'capital', country: 'CZ' },
  { name: 'Budapest', lat: 47.50, lng: 19.04, type: 'capital', country: 'HU' },
  { name: 'Bucharest', lat: 44.43, lng: 26.10, type: 'capital', country: 'RO' },
  { name: 'Athens', lat: 37.98, lng: 23.73, type: 'capital', country: 'GR' },
  { name: 'Lisbon', lat: 38.72, lng: -9.14, type: 'capital', country: 'PT' },
  { name: 'Kyiv', lat: 50.45, lng: 30.52, type: 'capital', country: 'UA' },
  { name: 'Baku', lat: 40.41, lng: 49.87, type: 'capital', country: 'AZ' },
  { name: 'Minsk', lat: 53.90, lng: 27.57, type: 'capital', country: 'BY' },
  { name: 'Riga', lat: 56.95, lng: 24.11, type: 'capital', country: 'LV' },
  { name: 'Tallinn', lat: 59.44, lng: 24.75, type: 'capital', country: 'EE' },
  { name: 'Vilnius', lat: 54.69, lng: 25.28, type: 'capital', country: 'LT' },
  { name: 'Sofia', lat: 42.70, lng: 23.32, type: 'capital', country: 'BG' },
  { name: 'Belgrade', lat: 44.82, lng: 20.46, type: 'capital', country: 'RS' },
  { name: 'Zagreb', lat: 45.82, lng: 15.98, type: 'capital', country: 'HR' },
  { name: 'Sarajevo', lat: 43.85, lng: 18.40, type: 'capital', country: 'BA' },
  { name: 'Tirana', lat: 41.33, lng: 19.82, type: 'capital', country: 'AL' },
  { name: 'Podgorica', lat: 42.44, lng: 19.26, type: 'capital', country: 'ME' },
  { name: 'Skopje', lat: 41.99, lng: 21.43, type: 'capital', country: 'MK' },
  { name: 'Chisinau', lat: 47.01, lng: 28.86, type: 'capital', country: 'MD' },
  { name: 'Tbilisi', lat: 41.69, lng: 44.83, type: 'capital', country: 'GE' },
  { name: 'Yerevan', lat: 40.18, lng: 44.51, type: 'capital', country: 'AM' },
  { name: 'Reykjavik', lat: 64.15, lng: -21.94, type: 'capital', country: 'IS' },
  { name: 'Luxembourg', lat: 49.61, lng: 6.13, type: 'capital', country: 'LU' },
  { name: 'Valletta', lat: 35.90, lng: 14.51, type: 'capital', country: 'MT' },
  { name: 'Nicosia', lat: 35.17, lng: 33.36, type: 'capital', country: 'CY' },
  { name: 'Bratislava', lat: 48.15, lng: 17.11, type: 'capital', country: 'SK' },
  { name: 'Ljubljana', lat: 46.05, lng: 14.50, type: 'capital', country: 'SI' },
  // Major EU Cities
  { name: 'Munich', lat: 48.14, lng: 11.58, type: 'major', country: 'DE' },
  { name: 'Hamburg', lat: 53.55, lng: 10.00, type: 'major', country: 'DE' },
  { name: 'Frankfurt', lat: 50.11, lng: 8.68, type: 'major', country: 'DE' },
  { name: 'Barcelona', lat: 41.39, lng: 2.16, type: 'major', country: 'ES' },
  { name: 'Milan', lat: 45.46, lng: 9.19, type: 'major', country: 'IT' },
  { name: 'Manchester', lat: 53.48, lng: -2.24, type: 'major', country: 'GB' },
  { name: 'Lyon', lat: 45.75, lng: 4.85, type: 'major', country: 'FR' },
  { name: 'Rotterdam', lat: 51.92, lng: 4.48, type: 'major', country: 'NL' },
  { name: 'Zurich', lat: 47.38, lng: 8.54, type: 'major', country: 'CH' },
  { name: 'Geneva', lat: 46.20, lng: 6.14, type: 'major', country: 'CH' },

  // --- NORTH AMERICA ---
  { name: 'Washington D.C.', lat: 38.91, lng: -77.04, type: 'capital', country: 'US' },
  { name: 'Ottawa', lat: 45.42, lng: -75.70, type: 'capital', country: 'CA' },
  { name: 'Mexico City', lat: 19.43, lng: -99.13, type: 'capital', country: 'MX' },
  { name: 'Havana', lat: 23.14, lng: -82.36, type: 'capital', country: 'CU' },
  { name: 'Nassau', lat: 25.05, lng: -77.34, type: 'capital', country: 'BS' },
  { name: 'Kingston', lat: 18.00, lng: -76.79, type: 'capital', country: 'JM' },
  { name: 'Port-au-Prince', lat: 18.54, lng: -72.34, type: 'capital', country: 'HT' },
  { name: 'Santo Domingo', lat: 18.48, lng: -69.90, type: 'capital', country: 'DO' },
  { name: 'San José', lat: 9.93, lng: -84.08, type: 'capital', country: 'CR' },
  { name: 'Guatemala City', lat: 14.64, lng: -90.51, type: 'capital', country: 'GT' },
  { name: 'Tegucigalpa', lat: 14.09, lng: -87.21, type: 'capital', country: 'HN' },
  { name: 'Managua', lat: 12.15, lng: -86.28, type: 'capital', country: 'NI' },
  { name: 'Panama City', lat: 8.99, lng: -79.52, type: 'capital', country: 'PA' },
  { name: 'San Salvador', lat: 13.69, lng: -89.19, type: 'capital', country: 'SV' },
  // Major NA Cities
  { name: 'New York', lat: 40.71, lng: -74.01, type: 'major', country: 'US' },
  { name: 'Los Angeles', lat: 34.05, lng: -118.24, type: 'major', country: 'US' },
  { name: 'Chicago', lat: 41.88, lng: -87.63, type: 'major', country: 'US' },
  { name: 'Houston', lat: 29.76, lng: -95.37, type: 'major', country: 'US' },
  { name: 'San Francisco', lat: 37.77, lng: -122.42, type: 'major', country: 'US' },
  { name: 'Seattle', lat: 47.61, lng: -122.33, type: 'major', country: 'US' },
  { name: 'Miami', lat: 25.77, lng: -80.19, type: 'major', country: 'US' },
  { name: 'Toronto', lat: 43.65, lng: -79.38, type: 'major', country: 'CA' },
  { name: 'Vancouver', lat: 49.25, lng: -123.12, type: 'major', country: 'CA' },
  { name: 'Guadalajara', lat: 20.66, lng: -103.35, type: 'major', country: 'MX' },

  // --- SOUTH AMERICA ---
  { name: 'Brasília', lat: -15.78, lng: -47.93, type: 'capital', country: 'BR' },
  { name: 'Buenos Aires', lat: -34.60, lng: -58.38, type: 'capital', country: 'AR' },
  { name: 'Santiago', lat: -33.46, lng: -70.65, type: 'capital', country: 'CL' },
  { name: 'Lima', lat: -12.05, lng: -77.04, type: 'capital', country: 'PE' },
  { name: 'Bogotá', lat: 4.71, lng: -74.07, type: 'capital', country: 'CO' },
  { name: 'Caracas', lat: 10.49, lng: -66.88, type: 'capital', country: 'VE' },
  { name: 'Montevideo', lat: -34.90, lng: -56.17, type: 'capital', country: 'UY' },
  { name: 'Asunción', lat: -25.29, lng: -57.65, type: 'capital', country: 'PY' },
  { name: 'Quito', lat: -0.22, lng: -78.51, type: 'capital', country: 'EC' },
  { name: 'La Paz', lat: -16.50, lng: -68.15, type: 'capital', country: 'BO' },
  { name: 'Georgetown', lat: 6.80, lng: -58.16, type: 'capital', country: 'GY' },
  { name: 'Paramaribo', lat: 5.87, lng: -55.17, type: 'capital', country: 'SR' },
  // Major SA cities
  { name: 'São Paulo', lat: -23.55, lng: -46.63, type: 'major', country: 'BR' },
  { name: 'Rio de Janeiro', lat: -22.91, lng: -43.17, type: 'major', country: 'BR' },
  { name: 'Medellín', lat: 6.25, lng: -75.56, type: 'major', country: 'CO' },

  // --- ASIA ---
  { name: 'Moscow', lat: 55.75, lng: 37.62, type: 'capital', country: 'RU' },
  { name: 'Beijing', lat: 39.91, lng: 116.39, type: 'capital', country: 'CN' },
  { name: 'Tokyo', lat: 35.69, lng: 139.69, type: 'capital', country: 'JP' },
  { name: 'Seoul', lat: 37.57, lng: 126.98, type: 'capital', country: 'KR' },
  { name: 'New Delhi', lat: 28.61, lng: 77.21, type: 'capital', country: 'IN' },
  { name: 'Islamabad', lat: 33.72, lng: 73.06, type: 'capital', country: 'PK' },
  { name: 'Dhaka', lat: 23.72, lng: 90.41, type: 'capital', country: 'BD' },
  { name: 'Kabul', lat: 34.53, lng: 69.17, type: 'capital', country: 'AF' },
  { name: 'Tehran', lat: 35.69, lng: 51.42, type: 'capital', country: 'IR' },
  { name: 'Baghdad', lat: 33.34, lng: 44.40, type: 'capital', country: 'IQ' },
  { name: 'Riyadh', lat: 24.69, lng: 46.72, type: 'capital', country: 'SA' },
  { name: 'Ankara', lat: 39.93, lng: 32.86, type: 'capital', country: 'TR' },
  { name: 'Amman', lat: 31.96, lng: 35.95, type: 'capital', country: 'JO' },
  { name: 'Jerusalem', lat: 31.78, lng: 35.22, type: 'capital', country: 'IL' },
  { name: 'Beirut', lat: 33.89, lng: 35.50, type: 'capital', country: 'LB' },
  { name: 'Damascus', lat: 33.51, lng: 36.29, type: 'capital', country: 'SY' },
  { name: 'Doha', lat: 25.29, lng: 51.53, type: 'capital', country: 'QA' },
  { name: 'Abu Dhabi', lat: 24.47, lng: 54.37, type: 'capital', country: 'AE' },
  { name: 'Kuwait City', lat: 29.37, lng: 47.98, type: 'capital', country: 'KW' },
  { name: 'Muscat', lat: 23.61, lng: 58.59, type: 'capital', country: 'OM' },
  { name: "Sana'a", lat: 15.35, lng: 44.21, type: 'capital', country: 'YE' },
  { name: 'Manama', lat: 26.22, lng: 50.59, type: 'capital', country: 'BH' },
  { name: 'Tashkent', lat: 41.30, lng: 69.27, type: 'capital', country: 'UZ' },
  { name: 'Astana', lat: 51.18, lng: 71.45, type: 'capital', country: 'KZ' },
  { name: 'Bishkek', lat: 42.87, lng: 74.59, type: 'capital', country: 'KG' },
  { name: 'Dushanbe', lat: 38.56, lng: 68.77, type: 'capital', country: 'TJ' },
  { name: 'Ashgabat', lat: 37.95, lng: 58.38, type: 'capital', country: 'TM' },
  { name: 'Ulaanbaatar', lat: 47.91, lng: 106.92, type: 'capital', country: 'MN' },
  { name: 'Pyongyang', lat: 39.03, lng: 125.75, type: 'capital', country: 'KP' },
  { name: 'Taipei', lat: 25.04, lng: 121.56, type: 'capital', country: 'TW' },
  { name: 'Bangkok', lat: 13.75, lng: 100.52, type: 'capital', country: 'TH' },
  { name: 'Hanoi', lat: 21.03, lng: 105.85, type: 'capital', country: 'VN' },
  { name: 'Vientiane', lat: 17.97, lng: 102.63, type: 'capital', country: 'LA' },
  { name: 'Phnom Penh', lat: 11.56, lng: 104.92, type: 'capital', country: 'KH' },
  { name: 'Naypyidaw', lat: 19.76, lng: 96.08, type: 'capital', country: 'MM' },
  { name: 'Jakarta', lat: -6.21, lng: 106.85, type: 'capital', country: 'ID' },
  { name: 'Manila', lat: 14.60, lng: 120.98, type: 'capital', country: 'PH' },
  { name: 'Kuala Lumpur', lat: 3.14, lng: 101.69, type: 'capital', country: 'MY' },
  { name: 'Singapore', lat: 1.35, lng: 103.82, type: 'capital', country: 'SG' },
  { name: 'Bandar Seri Begawan', lat: 4.94, lng: 114.95, type: 'capital', country: 'BN' },
  { name: 'Dili', lat: -8.56, lng: 125.58, type: 'capital', country: 'TL' },
  { name: 'Colombo', lat: 6.93, lng: 79.85, type: 'capital', country: 'LK' },
  { name: 'Kathmandu', lat: 27.72, lng: 85.32, type: 'capital', country: 'NP' },
  { name: 'Thimphu', lat: 27.47, lng: 89.64, type: 'capital', country: 'BT' },
  { name: 'Male', lat: 4.17, lng: 73.51, type: 'capital', country: 'MV' },
  // Major Asian Cities
  { name: 'Shanghai', lat: 31.23, lng: 121.47, type: 'major', country: 'CN' },
  { name: 'Shenzhen', lat: 22.54, lng: 114.06, type: 'major', country: 'CN' },
  { name: 'Guangzhou', lat: 23.13, lng: 113.26, type: 'major', country: 'CN' },
  { name: 'Chongqing', lat: 29.56, lng: 106.55, type: 'major', country: 'CN' },
  { name: 'Chengdu', lat: 30.66, lng: 104.07, type: 'major', country: 'CN' },
  { name: 'Osaka', lat: 34.69, lng: 135.50, type: 'major', country: 'JP' },
  { name: 'Mumbai', lat: 19.08, lng: 72.88, type: 'major', country: 'IN' },
  { name: 'Bangalore', lat: 12.97, lng: 77.59, type: 'major', country: 'IN' },
  { name: 'Chennai', lat: 13.08, lng: 80.27, type: 'major', country: 'IN' },
  { name: 'Karachi', lat: 24.86, lng: 67.01, type: 'major', country: 'PK' },
  { name: 'Lahore', lat: 31.55, lng: 74.34, type: 'major', country: 'PK' },
  { name: 'Istanbul', lat: 41.01, lng: 28.96, type: 'major', country: 'TR' },
  { name: 'Dubai', lat: 25.20, lng: 55.27, type: 'major', country: 'AE' },
  { name: 'Ho Chi Minh City', lat: 10.82, lng: 106.63, type: 'major', country: 'VN' },
  { name: 'Busan', lat: 35.10, lng: 129.04, type: 'major', country: 'KR' },
  { name: 'Jeddah', lat: 21.54, lng: 39.17, type: 'major', country: 'SA' },
  { name: 'St. Petersburg', lat: 59.94, lng: 30.32, type: 'major', country: 'RU' },
  { name: 'Novosibirsk', lat: 54.99, lng: 82.90, type: 'major', country: 'RU' },

  // --- AFRICA ---
  { name: 'Cairo', lat: 30.04, lng: 31.24, type: 'capital', country: 'EG' },
  { name: 'Addis Ababa', lat: 9.03, lng: 38.74, type: 'capital', country: 'ET' },
  { name: 'Nairobi', lat: -1.29, lng: 36.82, type: 'capital', country: 'KE' },
  { name: 'Lagos', lat: 6.52, lng: 3.38, type: 'major', country: 'NG' },
  { name: 'Abuja', lat: 9.07, lng: 7.40, type: 'capital', country: 'NG' },
  { name: 'Pretoria', lat: -25.75, lng: 28.19, type: 'capital', country: 'ZA' },
  { name: 'Johannesburg', lat: -26.20, lng: 28.04, type: 'major', country: 'ZA' },
  { name: 'Cape Town', lat: -33.92, lng: 18.42, type: 'major', country: 'ZA' },
  { name: 'Accra', lat: 5.56, lng: -0.20, type: 'capital', country: 'GH' },
  { name: 'Dakar', lat: 14.72, lng: -17.47, type: 'capital', country: 'SN' },
  { name: 'Algiers', lat: 36.74, lng: 3.06, type: 'capital', country: 'DZ' },
  { name: 'Tunis', lat: 36.82, lng: 10.17, type: 'capital', country: 'TN' },
  { name: 'Rabat', lat: 34.02, lng: -6.85, type: 'capital', country: 'MA' },
  { name: 'Casablanca', lat: 33.59, lng: -7.62, type: 'major', country: 'MA' },
  { name: 'Tripoli', lat: 32.90, lng: 13.18, type: 'capital', country: 'LY' },
  { name: 'Khartoum', lat: 15.55, lng: 32.53, type: 'capital', country: 'SD' },
  { name: 'Kampala', lat: 0.31, lng: 32.58, type: 'capital', country: 'UG' },
  { name: 'Dar es Salaam', lat: -6.78, lng: 39.27, type: 'major', country: 'TZ' },
  { name: 'Dodoma', lat: -6.18, lng: 35.74, type: 'capital', country: 'TZ' },
  { name: 'Kigali', lat: -1.95, lng: 30.06, type: 'capital', country: 'RW' },
  { name: 'Harare', lat: -17.83, lng: 31.05, type: 'capital', country: 'ZW' },
  { name: 'Lusaka', lat: -15.42, lng: 28.28, type: 'capital', country: 'ZM' },
  { name: 'Maputo', lat: -25.97, lng: 32.59, type: 'capital', country: 'MZ' },
  { name: 'Antananarivo', lat: -18.91, lng: 47.54, type: 'capital', country: 'MG' },
  { name: 'Luanda', lat: -8.84, lng: 13.23, type: 'capital', country: 'AO' },
  { name: 'Kinshasa', lat: -4.33, lng: 15.32, type: 'capital', country: 'CD' },
  { name: 'Brazzaville', lat: -4.27, lng: 15.28, type: 'capital', country: 'CG' },
  { name: 'Libreville', lat: 0.39, lng: 9.45, type: 'capital', country: 'GA' },
  { name: 'Yaoundé', lat: 3.87, lng: 11.52, type: 'capital', country: 'CM' },
  { name: 'Bamako', lat: 12.65, lng: -8.00, type: 'capital', country: 'ML' },
  { name: 'Niamey', lat: 13.51, lng: 2.12, type: 'capital', country: 'NE' },
  { name: "N'Djamena", lat: 12.11, lng: 15.04, type: 'capital', country: 'TD' },
  { name: 'Ouagadougou', lat: 12.37, lng: -1.53, type: 'capital', country: 'BF' },
  { name: 'Conakry', lat: 9.54, lng: -13.68, type: 'capital', country: 'GN' },
  { name: 'Freetown', lat: 8.49, lng: -13.23, type: 'capital', country: 'SL' },
  { name: 'Monrovia', lat: 6.30, lng: -10.80, type: 'capital', country: 'LR' },
  { name: 'Abidjan', lat: 5.36, lng: -4.01, type: 'major', country: 'CI' },
  { name: 'Mogadishu', lat: 2.05, lng: 45.34, type: 'capital', country: 'SO' },
  { name: 'Djibouti', lat: 11.59, lng: 43.15, type: 'capital', country: 'DJ' },
  { name: 'Asmara', lat: 15.33, lng: 38.93, type: 'capital', country: 'ER' },
  { name: 'Juba', lat: 4.86, lng: 31.57, type: 'capital', country: 'SS' },
  { name: 'Bangui', lat: 4.36, lng: 18.56, type: 'capital', country: 'CF' },
  { name: 'Malabo', lat: 3.75, lng: 8.78, type: 'capital', country: 'GQ' },
  { name: 'Maseru', lat: -29.32, lng: 27.48, type: 'capital', country: 'LS' },
  { name: 'Mbabane', lat: -26.32, lng: 31.13, type: 'capital', country: 'SZ' },
  { name: 'Windhoek', lat: -22.56, lng: 17.08, type: 'capital', country: 'NA' },
  { name: 'Gaborone', lat: -24.65, lng: 25.91, type: 'capital', country: 'BW' },
  { name: 'Lilongwe', lat: -13.97, lng: 33.79, type: 'capital', country: 'MW' },
  { name: 'Banjul', lat: 13.45, lng: -16.58, type: 'capital', country: 'GM' },
  { name: 'Bissau', lat: 11.86, lng: -15.60, type: 'capital', country: 'GW' },
  { name: 'Porto-Novo', lat: 6.37, lng: 2.42, type: 'capital', country: 'BJ' },
  { name: 'Lomé', lat: 6.14, lng: 1.22, type: 'capital', country: 'TG' },

  // --- OCEANIA ---
  { name: 'Canberra', lat: -35.28, lng: 149.13, type: 'capital', country: 'AU' },
  { name: 'Wellington', lat: -41.29, lng: 174.78, type: 'capital', country: 'NZ' },
  { name: 'Port Moresby', lat: -9.44, lng: 147.19, type: 'capital', country: 'PG' },
  { name: 'Suva', lat: -18.14, lng: 178.44, type: 'capital', country: 'FJ' },
  { name: 'Honiara', lat: -9.43, lng: 159.96, type: 'capital', country: 'SB' },
  { name: 'Port Vila', lat: -17.74, lng: 168.32, type: 'capital', country: 'VU' },
  // Major AU Cities
  { name: 'Sydney', lat: -33.87, lng: 151.21, type: 'major', country: 'AU' },
  { name: 'Melbourne', lat: -37.81, lng: 144.96, type: 'major', country: 'AU' },
  { name: 'Brisbane', lat: -27.47, lng: 153.03, type: 'major', country: 'AU' },
  { name: 'Auckland', lat: -36.86, lng: 174.77, type: 'major', country: 'NZ' },
];
