// ISO 3166-1 alpha-2 mapping for all world countries
export const COUNTRY_ISO_MAP = {
  'afghanistan': 'AF', 'albania': 'AL', 'algeria': 'DZ', 'andorra': 'AD', 'angola': 'AO',
  'argentina': 'AR', 'armenia': 'AM', 'australia': 'AU', 'austria': 'AT', 'azerbaijan': 'AZ',
  'bahamas': 'BS', 'bahrain': 'BH', 'bangladesh': 'BD', 'barbados': 'BB', 'belarus': 'BY',
  'belgium': 'BE', 'belize': 'BZ', 'benin': 'BJ', 'bhutan': 'BT', 'bolivia': 'BO',
  'bosnia & herz.': 'BA', 'bosnia': 'BA', 'botswana': 'BW', 'brazil': 'BR', 'brunei': 'BN',
  'bulgaria': 'BG', 'burkina faso': 'BF', 'burundi': 'BI', 'cabo verde': 'CV', 'cambodia': 'KH',
  'cameroon': 'CM', 'canada': 'CA', 'chad': 'TD', 'chile': 'CL', 'china': 'CN', 'colombia': 'CO',
  'congo': 'CG', 'dr congo': 'CD', 'costa rica': 'CR', 'croatia': 'HR', 'cuba': 'CU',
  'cyprus': 'CY', 'czech rep.': 'CZ', 'czechia': 'CZ', 'denmark': 'DK', 'ecuador': 'EC',
  'egypt': 'EG', 'estonia': 'EE', 'ethiopia': 'ET', 'finland': 'FI', 'france': 'FR',
  'georgia': 'GE', 'germany': 'DE', 'ghana': 'GH', 'greece': 'GR', 'guatemala': 'GT',
  'honduras': 'HN', 'hungary': 'HU', 'iceland': 'IS', 'india': 'IN', 'indonesia': 'ID',
  'iran': 'IR', 'iraq': 'IQ', 'ireland': 'IE', 'israel': 'IL', 'italy': 'IT', 'japan': 'JP',
  'jordan': 'JO', 'kazakhstan': 'KZ', 'kenya': 'KE', 'kuwait': 'KW', 'latvia': 'LV',
  'lebanon': 'LB', 'libya': 'LY', 'lithuania': 'LT', 'luxembourg': 'LU', 'malaysia': 'MY',
  'mexico': 'MX', 'moldova': 'MD', 'mongolia': 'MN', 'morocco': 'MA', 'netherlands': 'NL',
  'new zealand': 'NZ', 'nigeria': 'NG', 'norway': 'NO', 'oman': 'OM', 'pakistan': 'PK',
  'panama': 'PA', 'peru': 'PE', 'philippines': 'PH', 'poland': 'PL', 'portugal': 'PT',
  'qatar': 'QA', 'romania': 'RO', 'russia': 'RU', 'saudi arabia': 'SA', 'serbia': 'RS',
  'singapore': 'SG', 'slovakia': 'SK', 'slovenia': 'SI', 'south africa': 'ZA', 'south korea': 'KR',
  'spain': 'ES', 'sweden': 'SE', 'switzerland': 'CH', 'syria': 'SY', 'taiwan': 'TW',
  'thailand': 'TH', 'tunisia': 'TN', 'turkey': 'TR', 'turkmenistan': 'TM', 'ukraine': 'UA',
  'united arab emirates': 'AE', 'united kingdom': 'GB', 'united states': 'US', 'uruguay': 'UY',
  'uzbekistan': 'UZ', 'venezuela': 'VE', 'vietnam': 'VN', 'yemen': 'YE', 'zimbabwe': 'ZW',
  'são tomé and príncipe': 'ST', 'sao tome': 'ST'
};

export function getCountryIsoCode(countryName) {
  if (!countryName) return 'UN';
  const clean = countryName.trim().toLowerCase();
  if (clean.length === 2 && /^[a-z]{2}$/i.test(clean)) {
    return clean.toUpperCase();
  }
  return COUNTRY_ISO_MAP[clean] || (clean.length >= 2 ? clean.substring(0, 2).toUpperCase() : 'UN');
}

// All world countries with display names and center coordinates
export const ALL_COUNTRIES = [
  { name: 'Afghanistan', code: 'AF', lat: 33.9, lng: 67.7 },
  { name: 'Albania', code: 'AL', lat: 41.2, lng: 20.2 },
  { name: 'Algeria', code: 'DZ', lat: 28.0, lng: 2.6 },
  { name: 'Andorra', code: 'AD', lat: 42.5, lng: 1.5 },
  { name: 'Angola', code: 'AO', lat: -11.2, lng: 17.9 },
  { name: 'Argentina', code: 'AR', lat: -38.4, lng: -63.6 },
  { name: 'Armenia', code: 'AM', lat: 40.1, lng: 45.0 },
  { name: 'Australia', code: 'AU', lat: -25.3, lng: 133.8 },
  { name: 'Austria', code: 'AT', lat: 47.5, lng: 14.6 },
  { name: 'Azerbaijan', code: 'AZ', lat: 40.1, lng: 47.6 },
  { name: 'Bahamas', code: 'BS', lat: 25.0, lng: -77.4 },
  { name: 'Bahrain', code: 'BH', lat: 26.0, lng: 50.6 },
  { name: 'Bangladesh', code: 'BD', lat: 23.7, lng: 90.4 },
  { name: 'Belarus', code: 'BY', lat: 53.7, lng: 27.9 },
  { name: 'Belgium', code: 'BE', lat: 50.5, lng: 4.5 },
  { name: 'Bolivia', code: 'BO', lat: -16.3, lng: -63.6 },
  { name: 'Bosnia & Herz.', code: 'BA', lat: 44.2, lng: 17.7 },
  { name: 'Botswana', code: 'BW', lat: -22.3, lng: 24.7 },
  { name: 'Brazil', code: 'BR', lat: -14.2, lng: -51.9 },
  { name: 'Bulgaria', code: 'BG', lat: 42.7, lng: 25.5 },
  { name: 'Cambodia', code: 'KH', lat: 12.6, lng: 104.9 },
  { name: 'Cameroon', code: 'CM', lat: 3.9, lng: 11.5 },
  { name: 'Canada', code: 'CA', lat: 56.1, lng: -106.3 },
  { name: 'Chile', code: 'CL', lat: -35.7, lng: -71.5 },
  { name: 'China', code: 'CN', lat: 35.9, lng: 104.2 },
  { name: 'Colombia', code: 'CO', lat: 4.6, lng: -74.3 },
  { name: 'Costa Rica', code: 'CR', lat: 9.7, lng: -83.8 },
  { name: 'Croatia', code: 'HR', lat: 45.1, lng: 15.2 },
  { name: 'Cuba', code: 'CU', lat: 21.5, lng: -79.5 },
  { name: 'Cyprus', code: 'CY', lat: 35.1, lng: 33.4 },
  { name: 'Czech Rep.', code: 'CZ', lat: 49.8, lng: 15.5 },
  { name: 'Denmark', code: 'DK', lat: 56.3, lng: 9.5 },
  { name: 'Ecuador', code: 'EC', lat: -1.8, lng: -78.2 },
  { name: 'Egypt', code: 'EG', lat: 26.8, lng: 30.8 },
  { name: 'Estonia', code: 'EE', lat: 58.6, lng: 25.0 },
  { name: 'Ethiopia', code: 'ET', lat: 9.1, lng: 40.5 },
  { name: 'Finland', code: 'FI', lat: 61.9, lng: 25.7 },
  { name: 'France', code: 'FR', lat: 46.2, lng: 2.2 },
  { name: 'Georgia', code: 'GE', lat: 42.3, lng: 43.4 },
  { name: 'Germany', code: 'DE', lat: 51.2, lng: 10.4 },
  { name: 'Ghana', code: 'GH', lat: 7.9, lng: -1.0 },
  { name: 'Greece', code: 'GR', lat: 39.1, lng: 21.8 },
  { name: 'Hungary', code: 'HU', lat: 47.2, lng: 19.5 },
  { name: 'Iceland', code: 'IS', lat: 64.9, lng: -19.0 },
  { name: 'India', code: 'IN', lat: 20.6, lng: 79.0 },
  { name: 'Indonesia', code: 'ID', lat: -0.8, lng: 113.9 },
  { name: 'Iran', code: 'IR', lat: 32.4, lng: 53.7 },
  { name: 'Iraq', code: 'IQ', lat: 33.2, lng: 43.7 },
  { name: 'Ireland', code: 'IE', lat: 53.1, lng: -7.7 },
  { name: 'Israel', code: 'IL', lat: 31.0, lng: 34.9 },
  { name: 'Italy', code: 'IT', lat: 41.9, lng: 12.6 },
  { name: 'Japan', code: 'JP', lat: 36.2, lng: 138.3 },
  { name: 'Jordan', code: 'JO', lat: 30.6, lng: 36.3 },
  { name: 'Kazakhstan', code: 'KZ', lat: 48.0, lng: 66.9 },
  { name: 'Kenya', code: 'KE', lat: -0.0, lng: 37.9 },
  { name: 'Kuwait', code: 'KW', lat: 29.3, lng: 47.5 },
  { name: 'Latvia', code: 'LV', lat: 56.9, lng: 24.6 },
  { name: 'Lebanon', code: 'LB', lat: 33.9, lng: 35.9 },
  { name: 'Libya', code: 'LY', lat: 26.3, lng: 17.2 },
  { name: 'Lithuania', code: 'LT', lat: 55.2, lng: 23.9 },
  { name: 'Luxembourg', code: 'LU', lat: 49.8, lng: 6.1 },
  { name: 'Malaysia', code: 'MY', lat: 4.2, lng: 101.9 },
  { name: 'Mexico', code: 'MX', lat: 23.6, lng: -102.6 },
  { name: 'Moldova', code: 'MD', lat: 47.4, lng: 28.4 },
  { name: 'Mongolia', code: 'MN', lat: 46.9, lng: 103.8 },
  { name: 'Morocco', code: 'MA', lat: 31.8, lng: -7.1 },
  { name: 'Netherlands', code: 'NL', lat: 52.1, lng: 5.3 },
  { name: 'New Zealand', code: 'NZ', lat: -40.9, lng: 174.9 },
  { name: 'Nigeria', code: 'NG', lat: 9.1, lng: 8.7 },
  { name: 'Norway', code: 'NO', lat: 60.5, lng: 8.5 },
  { name: 'Oman', code: 'OM', lat: 21.5, lng: 55.9 },
  { name: 'Pakistan', code: 'PK', lat: 30.4, lng: 69.3 },
  { name: 'Panama', code: 'PA', lat: 8.5, lng: -80.8 },
  { name: 'Peru', code: 'PE', lat: -9.2, lng: -75.0 },
  { name: 'Philippines', code: 'PH', lat: 12.9, lng: 121.8 },
  { name: 'Poland', code: 'PL', lat: 51.9, lng: 19.1 },
  { name: 'Portugal', code: 'PT', lat: 39.4, lng: -8.2 },
  { name: 'Qatar', code: 'QA', lat: 25.4, lng: 51.2 },
  { name: 'Romania', code: 'RO', lat: 45.9, lng: 25.0 },
  { name: 'Russia', code: 'RU', lat: 61.5, lng: 105.3 },
  { name: 'Saudi Arabia', code: 'SA', lat: 23.9, lng: 45.1 },
  { name: 'Serbia', code: 'RS', lat: 44.0, lng: 21.0 },
  { name: 'Singapore', code: 'SG', lat: 1.4, lng: 103.8 },
  { name: 'Slovakia', code: 'SK', lat: 48.7, lng: 19.7 },
  { name: 'Slovenia', code: 'SI', lat: 46.2, lng: 15.0 },
  { name: 'South Africa', code: 'ZA', lat: -30.6, lng: 22.9 },
  { name: 'South Korea', code: 'KR', lat: 35.9, lng: 127.8 },
  { name: 'Spain', code: 'ES', lat: 40.5, lng: -3.7 },
  { name: 'Sweden', code: 'SE', lat: 60.1, lng: 18.6 },
  { name: 'Switzerland', code: 'CH', lat: 46.8, lng: 8.2 },
  { name: 'Taiwan', code: 'TW', lat: 23.7, lng: 121.0 },
  { name: 'Thailand', code: 'TH', lat: 15.9, lng: 101.0 },
  { name: 'Tunisia', code: 'TN', lat: 33.9, lng: 9.5 },
  { name: 'Turkey', code: 'TR', lat: 39.0, lng: 35.2 },
  { name: 'Ukraine', code: 'UA', lat: 48.4, lng: 31.2 },
  { name: 'United Arab Emirates', code: 'AE', lat: 23.4, lng: 53.8 },
  { name: 'United Kingdom', code: 'GB', lat: 55.4, lng: -3.4 },
  { name: 'United States', code: 'US', lat: 37.1, lng: -95.7 },
  { name: 'Uruguay', code: 'UY', lat: -32.5, lng: -55.8 },
  { name: 'Uzbekistan', code: 'UZ', lat: 41.4, lng: 64.6 },
  { name: 'Venezuela', code: 'VE', lat: 6.4, lng: -66.6 },
  { name: 'Vietnam', code: 'VN', lat: 14.1, lng: 108.3 }
];

export const ISO_TO_COUNTRY_MAP = Object.fromEntries(
  ALL_COUNTRIES.map(c => [c.code, c])
);

export function getCountryByIsoCode(isoCode) {
  if (!isoCode) return { name: 'Unknown', code: 'UN', lat: 20, lng: 0 };
  const upper = isoCode.toUpperCase();
  return ISO_TO_COUNTRY_MAP[upper] || { name: isoCode, code: upper, lat: 20, lng: 0 };
}
